.PHONY: clean All

All:
	@echo "----------Building project:[ LAB8 - Debug ]----------"
	@"$(MAKE)" -f  "LAB8.mk"
clean:
	@echo "----------Cleaning project:[ LAB8 - Debug ]----------"
	@"$(MAKE)" -f  "LAB8.mk" clean
